import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const schemaPath = path.join(root, "openapi", "frontend.openapi.json");
const outputPath = path.join(root, "src", "js", "api", "generated", "frontend-client.js");

function methodName(operationId) {
  return operationId.replace(/[^a-zA-Z0-9_$]/g, "_");
}

function renderClient(schema) {
  const operations = [];
  for (const [route, pathItem] of Object.entries(schema.paths)) {
    for (const method of ["get", "post", "put", "patch", "delete"]) {
      const operation = pathItem[method];
      if (!operation) continue;
      operations.push({ route, method: method.toUpperCase(), operationId: operation.operationId });
    }
  }
  operations.sort((a, b) => a.operationId.localeCompare(b.operationId));
  const methods = operations.map(({ route, method, operationId }) => {
    const pathParams = [...route.matchAll(/\{([^}]+)\}/g)].map((match) => match[1]);
    const args = [...pathParams, "options = {}"].join(", ");
    let expression = JSON.stringify(route);
    for (const parameter of pathParams) {
      expression = `${expression}.replace(${JSON.stringify(`{${parameter}}`)}, encodeURIComponent(${parameter}))`;
    }
    return `  ${methodName(operationId)}(${args}) {\n    const path = ${expression};\n    return this.transport.request({ path, method: ${JSON.stringify(method)}, ...options });\n  }`;
  }).join("\n\n");
  return `// Generated by tools/generate-client.mjs. Do not edit.\nexport const FRONTEND_OPERATION_IDS = ${JSON.stringify(operations.map((item) => item.operationId), null, 2)};\n\nexport class GeneratedFrontendClient {\n  constructor(transport) {\n    this.transport = transport;\n  }\n\n${methods}\n}\n`;
}

const schema = JSON.parse(await readFile(schemaPath, "utf8"));
const rendered = renderClient(schema);
if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== rendered) {
    console.error("Generated frontend client is out of sync. Run npm run build.");
    process.exit(1);
  }
} else {
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, rendered);
}
