"""core PostgreSQL authority model

Revision ID: 0002_core_authority_model
Revises: 0001_stage_a_baseline
Create Date: 2026-08-01 19:34:47.268468
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002_core_authority_model'
down_revision: str | None = '0001_stage_a_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authority_generations',
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('predecessor_generation_id', sa.Uuid(), nullable=True),
    sa.Column('creation_reason', sa.String(length=32), nullable=False),
    sa.Column('external_restore_control_id', sa.String(length=256), nullable=True),
    sa.Column('schema_head', sa.String(length=64), nullable=False),
    sa.Column('dish_release', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(creation_reason = 'initial_cutover' AND predecessor_generation_id IS NULL AND external_restore_control_id IS NULL) OR (creation_reason = 'destructive_restore' AND predecessor_generation_id IS NOT NULL AND external_restore_control_id IS NOT NULL)", name=op.f('ck_authority_generations_creation_provenance_complete')),
    sa.CheckConstraint("(status = 'retired' AND retired_at IS NOT NULL) OR (status IN ('pending','active') AND retired_at IS NULL)", name=op.f('ck_authority_generations_retirement_state_consistent')),
    sa.CheckConstraint("creation_reason IN ('initial_cutover','destructive_restore')", name=op.f('ck_authority_generations_creation_reason_allowed')),
    sa.CheckConstraint("status IN ('pending','active','retired')", name=op.f('ck_authority_generations_status_allowed')),
    sa.CheckConstraint('predecessor_generation_id IS NULL OR predecessor_generation_id <> generation_id', name=op.f('ck_authority_generations_predecessor_not_self')),
    sa.ForeignKeyConstraint(['predecessor_generation_id'], ['authority_generations.generation_id'], name=op.f('fk_authority_generations_predecessor_generation_id_authority_generations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('generation_id', name=op.f('pk_authority_generations')),
    sa.UniqueConstraint('external_restore_control_id', name=op.f('uq_authority_generations_external_restore_control_id'))
    )
    op.create_index('uq_authority_generations_one_active', 'authority_generations', ['status'], unique=True, postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    op.create_table('honest_contract_bindings',
    sa.Column('binding_id', sa.Uuid(), nullable=False),
    sa.Column('binding_kind', sa.String(length=24), nullable=False),
    sa.Column('source_identity', sa.String(length=512), nullable=False),
    sa.Column('dish_release', sa.String(length=128), nullable=False),
    sa.Column('honest_release', sa.String(length=128), nullable=False),
    sa.Column('protocol_release', sa.String(length=128), nullable=False),
    sa.Column('protocol_sha256', sa.String(length=64), nullable=False),
    sa.Column('schema_release', sa.String(length=128), nullable=False),
    sa.Column('schema_sha256', sa.String(length=64), nullable=False),
    sa.Column('migration_id', sa.String(length=128), nullable=True),
    sa.Column('source_schema_version', sa.String(length=64), nullable=True),
    sa.Column('target_schema_version', sa.String(length=64), nullable=True),
    sa.Column('migration_metadata_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_ids', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(binding_kind <> 'migration' AND migration_id IS NULL AND source_schema_version IS NULL AND target_schema_version IS NULL AND migration_metadata_sha256 IS NULL) OR (binding_kind = 'migration' AND migration_id IS NOT NULL AND source_schema_version IS NOT NULL AND target_schema_version IS NOT NULL AND length(migration_metadata_sha256) = 64)", name=op.f('ck_honest_contract_bindings_migration_fields_match_kind')),
    sa.CheckConstraint("binding_kind IN ('release','task_schema','migration')", name=op.f('ck_honest_contract_bindings_binding_kind_allowed')),
    sa.CheckConstraint('length(protocol_sha256) = 64', name=op.f('ck_honest_contract_bindings_protocol_hash_length')),
    sa.CheckConstraint('length(schema_sha256) = 64', name=op.f('ck_honest_contract_bindings_schema_hash_length')),
    sa.PrimaryKeyConstraint('binding_id', name=op.f('pk_honest_contract_bindings')),
    sa.UniqueConstraint('binding_kind', 'protocol_sha256', 'schema_sha256', 'migration_id', 'migration_metadata_sha256', name='uq_honest_binding_exact_identity')
    )
    op.create_table('stage_a_import_runs',
    sa.Column('import_run_id', sa.Uuid(), nullable=False),
    sa.Column('source_commit', sa.String(length=64), nullable=False),
    sa.Column('source_release', sa.String(length=128), nullable=False),
    sa.Column('legacy_generation_id', sa.String(length=128), nullable=False),
    sa.Column('baseline_high_water_mark', sa.String(length=256), nullable=False),
    sa.Column('source_bundle_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.CheckConstraint("(status = 'complete' AND completed_at IS NOT NULL) OR (status = 'failed' AND completed_at IS NOT NULL)", name=op.f('ck_stage_a_import_runs_terminal_has_completion')),
    sa.CheckConstraint("status IN ('complete','failed')", name=op.f('ck_stage_a_import_runs_status_allowed')),
    sa.CheckConstraint('length(source_bundle_sha256) = 64', name=op.f('ck_stage_a_import_runs_bundle_hash_length')),
    sa.PrimaryKeyConstraint('import_run_id', name=op.f('pk_stage_a_import_runs')),
    sa.UniqueConstraint('legacy_generation_id', 'baseline_high_water_mark', name='uq_import_run_legacy_high_water')
    )
    op.create_table('applied_migration_events',
    sa.Column('migration_event_id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.String(length=64), nullable=False),
    sa.Column('predecessor_revision', sa.String(length=64), nullable=True),
    sa.Column('migration_code_sha256', sa.String(length=64), nullable=False),
    sa.Column('dish_release', sa.String(length=128), nullable=False),
    sa.Column('initiator', sa.String(length=256), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminal_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.CheckConstraint("outcome IN ('applied','failed','repair','reversal','stamp')", name=op.f('ck_applied_migration_events_outcome_allowed')),
    sa.CheckConstraint('length(migration_code_sha256) = 64', name=op.f('ck_applied_migration_events_code_hash_length')),
    sa.ForeignKeyConstraint(['generation_id'], ['authority_generations.generation_id'], name=op.f('fk_applied_migration_events_generation_id_authority_generations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('migration_event_id', name=op.f('pk_applied_migration_events')),
    sa.UniqueConstraint('generation_id', 'revision', 'outcome', name='uq_migration_generation_revision_outcome')
    )
    op.create_table('authority_activations',
    sa.Column('activation_id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=False),
    sa.Column('cutover_approval_id', sa.String(length=256), nullable=False),
    sa.Column('legacy_bundle_id', sa.String(length=256), nullable=False),
    sa.Column('schema_head', sa.String(length=64), nullable=False),
    sa.Column('dish_release', sa.String(length=128), nullable=False),
    sa.Column('honest_release', sa.String(length=128), nullable=False),
    sa.Column('protocol_release', sa.String(length=128), nullable=False),
    sa.Column('openapi_release', sa.String(length=128), nullable=False),
    sa.Column('routing_release', sa.String(length=128), nullable=False),
    sa.Column('projection_epoch', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('rollback_burned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(outcome = 'activated' AND rollback_burned_at IS NOT NULL) OR (outcome = 'aborted' AND rollback_burned_at IS NULL)", name=op.f('ck_authority_activations_rollback_burn_matches_outcome')),
    sa.CheckConstraint("outcome IN ('activated','aborted')", name=op.f('ck_authority_activations_outcome_allowed')),
    sa.ForeignKeyConstraint(['generation_id'], ['authority_generations.generation_id'], name=op.f('fk_authority_activations_generation_id_authority_generations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_authority_activations_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('activation_id', name=op.f('pk_authority_activations')),
    sa.UniqueConstraint('generation_id', 'outcome', name='uq_activation_generation_outcome'),
    sa.UniqueConstraint('projection_epoch', name=op.f('uq_authority_activations_projection_epoch'))
    )
    op.create_table('dish_tasks',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('existence_state', sa.String(length=16), nullable=False),
    sa.Column('creation_route', sa.String(length=16), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=True),
    sa.Column('command_execution_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(creation_route = 'import' AND import_run_id IS NOT NULL AND command_execution_id IS NULL) OR (creation_route = 'create' AND import_run_id IS NULL AND command_execution_id IS NOT NULL)", name=op.f('ck_dish_tasks_exact_creation_provenance')),
    sa.CheckConstraint("(existence_state = 'retired' AND retired_at IS NOT NULL) OR (existence_state IN ('ordinary','isolated') AND retired_at IS NULL)", name=op.f('ck_dish_tasks_retirement_consistent')),
    sa.CheckConstraint("creation_route IN ('import','create')", name=op.f('ck_dish_tasks_creation_route_allowed')),
    sa.CheckConstraint("existence_state IN ('ordinary','isolated','retired')", name=op.f('ck_dish_tasks_existence_allowed')),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_dish_tasks_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_dish_tasks'))
    )
    op.create_table('generation_bootstrap_authorities',
    sa.Column('bootstrap_id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('external_control_id', sa.String(length=256), nullable=False),
    sa.Column('capability_digest', sa.LargeBinary(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('NOT (consumed_at IS NOT NULL AND retired_at IS NOT NULL)', name=op.f('ck_generation_bootstrap_authorities_single_terminal_route')),
    sa.ForeignKeyConstraint(['generation_id'], ['authority_generations.generation_id'], name=op.f('fk_generation_bootstrap_authorities_generation_id_authority_generations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('bootstrap_id', name=op.f('pk_generation_bootstrap_authorities')),
    sa.UniqueConstraint('external_control_id', name=op.f('uq_generation_bootstrap_authorities_external_control_id')),
    sa.UniqueConstraint('generation_id', name=op.f('uq_generation_bootstrap_authorities_generation_id'))
    )
    op.create_table('governed_projects',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('logical_name', sa.String(length=256), nullable=False),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(lifecycle = 'active' AND retired_at IS NULL) OR (lifecycle = 'retired' AND retired_at IS NOT NULL)", name=op.f('ck_governed_projects_retirement_consistent')),
    sa.CheckConstraint("lifecycle IN ('active','retired')", name=op.f('ck_governed_projects_lifecycle_allowed')),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_governed_projects_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_governed_projects')),
    sa.UniqueConstraint('logical_name', name=op.f('uq_governed_projects_logical_name'))
    )
    op.create_table('section_registry_versions',
    sa.Column('registry_version_id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=False),
    sa.Column('contract_binding_id', sa.Uuid(), nullable=False),
    sa.Column('registry_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(registry_sha256) = 64', name=op.f('ck_section_registry_versions_registry_hash_length')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_section_registry_versions_positive_version')),
    sa.ForeignKeyConstraint(['contract_binding_id'], ['honest_contract_bindings.binding_id'], name=op.f('fk_section_registry_versions_contract_binding_id_honest_contract_bindings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generation_id'], ['authority_generations.generation_id'], name=op.f('fk_section_registry_versions_generation_id_authority_generations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_section_registry_versions_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('registry_version_id', name=op.f('pk_section_registry_versions')),
    sa.UniqueConstraint('generation_id', 'version_number', name='uq_registry_generation_version')
    )
    op.create_table('governed_sections',
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('logical_name', sa.String(length=256), nullable=False),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(lifecycle = 'active' AND retired_at IS NULL) OR (lifecycle = 'retired' AND retired_at IS NOT NULL)", name=op.f('ck_governed_sections_retirement_consistent')),
    sa.CheckConstraint("lifecycle IN ('active','retired')", name=op.f('ck_governed_sections_lifecycle_allowed')),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_governed_sections_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['governed_projects.project_id'], name=op.f('fk_governed_sections_project_id_governed_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('section_id', name=op.f('pk_governed_sections')),
    sa.UniqueConstraint('project_id', 'logical_name', name='uq_section_project_name')
    )
    op.create_table('project_external_aliases',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('alias_id', sa.Uuid(), nullable=False),
    sa.Column('external_system', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=True),
    sa.Column('projection_event_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(origin = 'imported' AND import_run_id IS NOT NULL AND projection_event_id IS NULL) OR (origin = 'projection' AND import_run_id IS NULL AND projection_event_id IS NOT NULL)", name=op.f('ck_project_external_aliases_exact_origin_provenance')),
    sa.CheckConstraint("(state = 'active' AND retired_at IS NULL) OR (state = 'retired' AND retired_at IS NOT NULL)", name=op.f('ck_project_external_aliases_retirement_consistent')),
    sa.CheckConstraint("origin IN ('imported','projection')", name=op.f('ck_project_external_aliases_origin_allowed')),
    sa.CheckConstraint("state IN ('active','retired')", name=op.f('ck_project_external_aliases_state_allowed')),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_project_external_aliases_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['governed_projects.project_id'], name=op.f('fk_project_external_aliases_project_id_governed_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('alias_id', name=op.f('pk_project_external_aliases')),
    sa.UniqueConstraint('external_system', 'external_id', name='uq_project_external_alias_identity')
    )
    op.create_table('section_registry_activations',
    sa.Column('registry_activation_id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('registry_version_id', sa.Uuid(), nullable=False),
    sa.Column('activation_route', sa.String(length=24), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=True),
    sa.Column('command_execution_id', sa.Uuid(), nullable=True),
    sa.Column('registry_revision', sa.BigInteger(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(activation_route = 'import' AND import_run_id IS NOT NULL AND command_execution_id IS NULL) OR (activation_route = 'command_execution' AND import_run_id IS NULL AND command_execution_id IS NOT NULL)", name=op.f('ck_section_registry_activations_exact_provenance_route')),
    sa.CheckConstraint("activation_route IN ('import','command_execution')", name=op.f('ck_section_registry_activations_route_allowed')),
    sa.CheckConstraint('registry_revision > 0', name=op.f('ck_section_registry_activations_positive_revision')),
    sa.ForeignKeyConstraint(['generation_id'], ['authority_generations.generation_id'], name=op.f('fk_section_registry_activations_generation_id_authority_generations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_section_registry_activations_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registry_version_id'], ['section_registry_versions.registry_version_id'], name=op.f('fk_section_registry_activations_registry_version_id_section_registry_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('registry_activation_id', name=op.f('pk_section_registry_activations')),
    sa.UniqueConstraint('generation_id', 'registry_revision', name='uq_registry_activation_revision'),
    sa.UniqueConstraint('generation_id', 'registry_version_id', name='uq_registry_activation_version')
    )
    op.create_table('task_completion_events',
    sa.Column('completion_event_id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('completion_revision', sa.BigInteger(), nullable=False),
    sa.Column('provenance_route', sa.String(length=24), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=True),
    sa.Column('command_execution_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(provenance_route = 'import' AND import_run_id IS NOT NULL AND command_execution_id IS NULL) OR (provenance_route = 'command_execution' AND import_run_id IS NULL AND command_execution_id IS NOT NULL)", name=op.f('ck_task_completion_events_exact_provenance_route')),
    sa.CheckConstraint("(reason = 'imported' AND provenance_route = 'import') OR (reason IN ('cooked','archive','reopen_planning') AND provenance_route = 'command_execution')", name=op.f('ck_task_completion_events_reason_matches_route')),
    sa.CheckConstraint("provenance_route IN ('import','command_execution')", name=op.f('ck_task_completion_events_route_allowed')),
    sa.CheckConstraint("reason IN ('imported','cooked','archive','reopen_planning')", name=op.f('ck_task_completion_events_reason_allowed')),
    sa.CheckConstraint('completion_revision > 0', name=op.f('ck_task_completion_events_positive_revision')),
    sa.ForeignKeyConstraint(['generation_id'], ['authority_generations.generation_id'], name=op.f('fk_task_completion_events_generation_id_authority_generations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_task_completion_events_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['dish_tasks.task_id'], name=op.f('fk_task_completion_events_task_id_dish_tasks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('completion_event_id', name=op.f('pk_task_completion_events')),
    sa.UniqueConstraint('generation_id', 'task_id', 'completion_revision', name='uq_completion_event_revision')
    )
    op.create_table('task_content_versions',
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('representation_kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('identity_scheme', sa.String(length=64), nullable=False),
    sa.Column('content_identity', sa.String(length=256), nullable=False),
    sa.Column('creator_route', sa.String(length=24), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=True),
    sa.Column('command_execution_id', sa.Uuid(), nullable=True),
    sa.Column('predecessor_content_version_id', sa.Uuid(), nullable=True),
    sa.Column('contract_binding_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(creator_route = 'import' AND import_run_id IS NOT NULL AND command_execution_id IS NULL) OR (creator_route = 'command_execution' AND import_run_id IS NULL AND command_execution_id IS NOT NULL)", name=op.f('ck_task_content_versions_exact_creator_provenance')),
    sa.CheckConstraint("creator_route IN ('import','command_execution')", name=op.f('ck_task_content_versions_creator_route_allowed')),
    sa.CheckConstraint("representation_kind = 'document'", name=op.f('ck_task_content_versions_document_only')),
    sa.CheckConstraint('length(content_identity) > 0', name=op.f('ck_task_content_versions_identity_nonblank')),
    sa.CheckConstraint('length(trim(title)) > 0', name=op.f('ck_task_content_versions_title_nonblank')),
    sa.CheckConstraint('predecessor_content_version_id IS NULL OR predecessor_content_version_id <> content_version_id', name=op.f('ck_task_content_versions_predecessor_not_self')),
    sa.ForeignKeyConstraint(['contract_binding_id'], ['honest_contract_bindings.binding_id'], name=op.f('fk_task_content_versions_contract_binding_id_honest_contract_bindings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generation_id'], ['authority_generations.generation_id'], name=op.f('fk_task_content_versions_generation_id_authority_generations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_task_content_versions_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generation_id', 'task_id', 'predecessor_content_version_id'], ['task_content_versions.generation_id', 'task_content_versions.task_id', 'task_content_versions.content_version_id'], name='fk_content_version_exact_predecessor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['dish_tasks.task_id'], name=op.f('fk_task_content_versions_task_id_dish_tasks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('content_version_id', name=op.f('pk_task_content_versions')),
    sa.UniqueConstraint('generation_id', 'task_id', 'content_version_id', name='uq_content_generation_task_id'),
    sa.UniqueConstraint('generation_id', 'task_id', 'identity_scheme', 'content_identity', name='uq_content_exact_identity')
    )
    op.create_table('task_external_aliases',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('alias_id', sa.Uuid(), nullable=False),
    sa.Column('external_system', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=True),
    sa.Column('projection_event_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(origin = 'imported' AND import_run_id IS NOT NULL AND projection_event_id IS NULL) OR (origin = 'projection' AND import_run_id IS NULL AND projection_event_id IS NOT NULL)", name=op.f('ck_task_external_aliases_exact_origin_provenance')),
    sa.CheckConstraint("(state = 'active' AND retired_at IS NULL) OR (state = 'retired' AND retired_at IS NOT NULL)", name=op.f('ck_task_external_aliases_retirement_consistent')),
    sa.CheckConstraint("origin IN ('imported','projection')", name=op.f('ck_task_external_aliases_origin_allowed')),
    sa.CheckConstraint("state IN ('active','retired')", name=op.f('ck_task_external_aliases_state_allowed')),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_task_external_aliases_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['dish_tasks.task_id'], name=op.f('fk_task_external_aliases_task_id_dish_tasks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('alias_id', name=op.f('pk_task_external_aliases')),
    sa.UniqueConstraint('external_system', 'external_id', name='uq_task_external_alias_identity')
    )
    op.create_table('task_project_membership_events',
    sa.Column('membership_event_id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('event_kind', sa.String(length=16), nullable=False),
    sa.Column('membership_revision', sa.BigInteger(), nullable=False),
    sa.Column('provenance_route', sa.String(length=24), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=True),
    sa.Column('command_execution_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(provenance_route = 'import' AND import_run_id IS NOT NULL AND command_execution_id IS NULL) OR (provenance_route = 'command_execution' AND import_run_id IS NULL AND command_execution_id IS NOT NULL)", name=op.f('ck_task_project_membership_events_exact_provenance_route')),
    sa.CheckConstraint("event_kind IN ('joined','left')", name=op.f('ck_task_project_membership_events_event_kind_allowed')),
    sa.CheckConstraint("provenance_route IN ('import','command_execution')", name=op.f('ck_task_project_membership_events_route_allowed')),
    sa.CheckConstraint('membership_revision > 0', name=op.f('ck_task_project_membership_events_positive_revision')),
    sa.ForeignKeyConstraint(['generation_id'], ['authority_generations.generation_id'], name=op.f('fk_task_project_membership_events_generation_id_authority_generations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_task_project_membership_events_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['governed_projects.project_id'], name=op.f('fk_task_project_membership_events_project_id_governed_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['dish_tasks.task_id'], name=op.f('fk_task_project_membership_events_task_id_dish_tasks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('membership_event_id', name=op.f('pk_task_project_membership_events')),
    sa.UniqueConstraint('generation_id', 'task_id', 'project_id', 'membership_revision', name='uq_membership_event_revision')
    )
    op.create_table('active_section_registries',
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('registry_version_id', sa.Uuid(), nullable=False),
    sa.Column('registry_activation_id', sa.Uuid(), nullable=False),
    sa.Column('registry_revision', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('registry_revision > 0', name=op.f('ck_active_section_registries_positive_revision')),
    sa.ForeignKeyConstraint(['generation_id'], ['authority_generations.generation_id'], name=op.f('fk_active_section_registries_generation_id_authority_generations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registry_activation_id'], ['section_registry_activations.registry_activation_id'], name=op.f('fk_active_section_registries_registry_activation_id_section_registry_activations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registry_version_id'], ['section_registry_versions.registry_version_id'], name=op.f('fk_active_section_registries_registry_version_id_section_registry_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('generation_id', name=op.f('pk_active_section_registries')),
    sa.UniqueConstraint('registry_activation_id', name=op.f('uq_active_section_registries_registry_activation_id')),
    sa.UniqueConstraint('registry_version_id', name=op.f('uq_active_section_registries_registry_version_id'))
    )
    op.create_table('section_external_aliases',
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('alias_id', sa.Uuid(), nullable=False),
    sa.Column('external_system', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=True),
    sa.Column('projection_event_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(origin = 'imported' AND import_run_id IS NOT NULL AND projection_event_id IS NULL) OR (origin = 'projection' AND import_run_id IS NULL AND projection_event_id IS NOT NULL)", name=op.f('ck_section_external_aliases_exact_origin_provenance')),
    sa.CheckConstraint("(state = 'active' AND retired_at IS NULL) OR (state = 'retired' AND retired_at IS NOT NULL)", name=op.f('ck_section_external_aliases_retirement_consistent')),
    sa.CheckConstraint("origin IN ('imported','projection')", name=op.f('ck_section_external_aliases_origin_allowed')),
    sa.CheckConstraint("state IN ('active','retired')", name=op.f('ck_section_external_aliases_state_allowed')),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_section_external_aliases_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['governed_sections.section_id'], name=op.f('fk_section_external_aliases_section_id_governed_sections'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('alias_id', name=op.f('pk_section_external_aliases')),
    sa.UniqueConstraint('external_system', 'external_id', name='uq_section_external_alias_identity')
    )
    op.create_table('section_registry_entries',
    sa.Column('registry_version_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('workflow_role', sa.String(length=64), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_section_registry_entries_nonnegative_ordinal')),
    sa.ForeignKeyConstraint(['registry_version_id'], ['section_registry_versions.registry_version_id'], name=op.f('fk_section_registry_entries_registry_version_id_section_registry_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['governed_sections.section_id'], name=op.f('fk_section_registry_entries_section_id_governed_sections'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('registry_version_id', 'section_id', name=op.f('pk_section_registry_entries')),
    sa.UniqueConstraint('registry_version_id', 'ordinal', name='uq_registry_entry_ordinal'),
    sa.UniqueConstraint('registry_version_id', 'workflow_role', name='uq_registry_entry_workflow_role')
    )
    op.create_table('task_content_activations',
    sa.Column('content_activation_id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('activation_route', sa.String(length=24), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=True),
    sa.Column('command_execution_id', sa.Uuid(), nullable=True),
    sa.Column('task_revision', sa.BigInteger(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(activation_route = 'import' AND import_run_id IS NOT NULL AND command_execution_id IS NULL) OR (activation_route = 'command_execution' AND import_run_id IS NULL AND command_execution_id IS NOT NULL)", name=op.f('ck_task_content_activations_exact_provenance_route')),
    sa.CheckConstraint("activation_route IN ('import','command_execution')", name=op.f('ck_task_content_activations_route_allowed')),
    sa.CheckConstraint('task_revision > 0', name=op.f('ck_task_content_activations_positive_task_revision')),
    sa.ForeignKeyConstraint(['generation_id', 'task_id', 'content_version_id'], ['task_content_versions.generation_id', 'task_content_versions.task_id', 'task_content_versions.content_version_id'], name='fk_content_activation_exact_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_task_content_activations_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('content_activation_id', name=op.f('pk_task_content_activations')),
    sa.UniqueConstraint('generation_id', 'task_id', 'content_version_id', name='uq_content_activation_version'),
    sa.UniqueConstraint('generation_id', 'task_id', 'task_revision', name='uq_content_activation_revision')
    )
    op.create_table('task_section_placement_events',
    sa.Column('placement_event_id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('registry_version_id', sa.Uuid(), nullable=False),
    sa.Column('event_kind', sa.String(length=16), nullable=False),
    sa.Column('placement_revision', sa.BigInteger(), nullable=False),
    sa.Column('provenance_route', sa.String(length=24), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=True),
    sa.Column('command_execution_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(event_kind = 'placed' AND section_id IS NOT NULL) OR (event_kind = 'cleared' AND section_id IS NULL)", name=op.f('ck_task_section_placement_events_section_matches_event')),
    sa.CheckConstraint("(provenance_route = 'import' AND import_run_id IS NOT NULL AND command_execution_id IS NULL) OR (provenance_route = 'command_execution' AND import_run_id IS NULL AND command_execution_id IS NOT NULL)", name=op.f('ck_task_section_placement_events_exact_provenance_route')),
    sa.CheckConstraint("event_kind IN ('placed','cleared')", name=op.f('ck_task_section_placement_events_event_kind_allowed')),
    sa.CheckConstraint("provenance_route IN ('import','command_execution')", name=op.f('ck_task_section_placement_events_route_allowed')),
    sa.CheckConstraint('placement_revision > 0', name=op.f('ck_task_section_placement_events_positive_revision')),
    sa.ForeignKeyConstraint(['generation_id'], ['authority_generations.generation_id'], name=op.f('fk_task_section_placement_events_generation_id_authority_generations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_run_id'], ['stage_a_import_runs.import_run_id'], name=op.f('fk_task_section_placement_events_import_run_id_stage_a_import_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registry_version_id'], ['section_registry_versions.registry_version_id'], name=op.f('fk_task_section_placement_events_registry_version_id_section_registry_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['governed_sections.section_id'], name=op.f('fk_task_section_placement_events_section_id_governed_sections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['dish_tasks.task_id'], name=op.f('fk_task_section_placement_events_task_id_dish_tasks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('placement_event_id', name=op.f('pk_task_section_placement_events')),
    sa.UniqueConstraint('generation_id', 'task_id', 'placement_revision', name='uq_placement_event_revision')
    )
    op.create_table('task_authority_heads',
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('current_content_activation_id', sa.Uuid(), nullable=False),
    sa.Column('task_revision', sa.BigInteger(), nullable=False),
    sa.Column('membership_revision', sa.BigInteger(), nullable=False),
    sa.Column('placement_revision', sa.BigInteger(), nullable=False),
    sa.Column('completion_revision', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('completion_revision > 0', name=op.f('ck_task_authority_heads_positive_completion_revision')),
    sa.CheckConstraint('membership_revision >= 0', name=op.f('ck_task_authority_heads_nonnegative_membership_revision')),
    sa.CheckConstraint('placement_revision >= 0', name=op.f('ck_task_authority_heads_nonnegative_placement_revision')),
    sa.CheckConstraint('task_revision > 0', name=op.f('ck_task_authority_heads_positive_task_revision')),
    sa.ForeignKeyConstraint(['current_content_activation_id'], ['task_content_activations.content_activation_id'], name=op.f('fk_task_authority_heads_current_content_activation_id_task_content_activations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generation_id'], ['authority_generations.generation_id'], name=op.f('fk_task_authority_heads_generation_id_authority_generations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['dish_tasks.task_id'], name=op.f('fk_task_authority_heads_task_id_dish_tasks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('generation_id', 'task_id', name=op.f('pk_task_authority_heads')),
    sa.UniqueConstraint('current_content_activation_id', name=op.f('uq_task_authority_heads_current_content_activation_id'))
    )
    op.create_table('current_task_completion',
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('latest_event_id', sa.Uuid(), nullable=False),
    sa.Column('completion_revision', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('completion_revision > 0', name=op.f('ck_current_task_completion_positive_revision')),
    sa.ForeignKeyConstraint(['generation_id', 'task_id'], ['task_authority_heads.generation_id', 'task_authority_heads.task_id'], name='fk_current_completion_task_head', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['latest_event_id'], ['task_completion_events.completion_event_id'], name=op.f('fk_current_task_completion_latest_event_id_task_completion_events'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('generation_id', 'task_id', name=op.f('pk_current_task_completion')),
    sa.UniqueConstraint('latest_event_id', name=op.f('uq_current_task_completion_latest_event_id'))
    )
    op.create_table('current_task_project_memberships',
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('latest_event_id', sa.Uuid(), nullable=False),
    sa.Column('is_member', sa.Boolean(), nullable=False),
    sa.Column('membership_revision', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('membership_revision > 0', name=op.f('ck_current_task_project_memberships_positive_revision')),
    sa.ForeignKeyConstraint(['generation_id', 'task_id'], ['task_authority_heads.generation_id', 'task_authority_heads.task_id'], name='fk_current_membership_task_head', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['latest_event_id'], ['task_project_membership_events.membership_event_id'], name=op.f('fk_current_task_project_memberships_latest_event_id_task_project_membership_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['governed_projects.project_id'], name=op.f('fk_current_task_project_memberships_project_id_governed_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('generation_id', 'task_id', 'project_id', name=op.f('pk_current_task_project_memberships')),
    sa.UniqueConstraint('latest_event_id', name=op.f('uq_current_task_project_memberships_latest_event_id'))
    )
    op.create_table('current_task_section_placements',
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('registry_version_id', sa.Uuid(), nullable=False),
    sa.Column('latest_event_id', sa.Uuid(), nullable=False),
    sa.Column('placement_revision', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('placement_revision > 0', name=op.f('ck_current_task_section_placements_positive_revision')),
    sa.ForeignKeyConstraint(['generation_id', 'task_id'], ['task_authority_heads.generation_id', 'task_authority_heads.task_id'], name='fk_current_placement_task_head', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['latest_event_id'], ['task_section_placement_events.placement_event_id'], name=op.f('fk_current_task_section_placements_latest_event_id_task_section_placement_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registry_version_id'], ['section_registry_versions.registry_version_id'], name=op.f('fk_current_task_section_placements_registry_version_id_section_registry_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['governed_sections.section_id'], name=op.f('fk_current_task_section_placements_section_id_governed_sections'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('generation_id', 'task_id', name=op.f('pk_current_task_section_placements')),
    sa.UniqueConstraint('latest_event_id', name=op.f('uq_current_task_section_placements_latest_event_id'))
    )
    _install_postgresql_authority_guards()
    # ### end Alembic commands ###


def _install_postgresql_authority_guards() -> None:
    if op.get_context().dialect.name != "postgresql":
        return
    op.execute(
        """
        CREATE OR REPLACE FUNCTION dish_reject_immutable_authority()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'immutable authority row: %', TG_TABLE_NAME
                USING ERRCODE = '23514';
        END;
        $$
        """
    )
    for table_name in (
        "authority_activations",
        "applied_migration_events",
        "honest_contract_bindings",
        "section_registry_versions",
        "section_registry_entries",
        "section_registry_activations",
        "task_content_versions",
        "task_content_activations",
        "task_project_membership_events",
        "task_section_placement_events",
        "task_completion_events",
    ):
        op.execute(
            f"""
            CREATE TRIGGER {table_name}_immutable_update
            BEFORE UPDATE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION dish_reject_immutable_authority();
            CREATE TRIGGER {table_name}_immutable_delete
            BEFORE DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION dish_reject_immutable_authority();
            """
        )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION dish_validate_generation_transition()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.generation_id <> NEW.generation_id
               OR OLD.creation_reason <> NEW.creation_reason
               OR OLD.predecessor_generation_id IS DISTINCT FROM NEW.predecessor_generation_id
               OR OLD.external_restore_control_id IS DISTINCT FROM NEW.external_restore_control_id
               OR OLD.schema_head <> NEW.schema_head
               OR OLD.dish_release <> NEW.dish_release
               OR OLD.created_at <> NEW.created_at THEN
                RAISE EXCEPTION 'authority generation identity is immutable' USING ERRCODE='23514';
            END IF;
            IF OLD.status = 'retired' OR
               (OLD.status = 'active' AND NEW.status NOT IN ('active','retired')) OR
               (OLD.status = 'pending' AND NEW.status NOT IN ('pending','active','retired')) THEN
                RAISE EXCEPTION 'illegal authority generation transition' USING ERRCODE='23514';
            END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER authority_generations_monotonic_update
        BEFORE UPDATE ON authority_generations
        FOR EACH ROW EXECUTE FUNCTION dish_validate_generation_transition();
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION dish_validate_active_registry_pointer()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                  FROM section_registry_versions v
                  JOIN section_registry_activations a
                    ON a.registry_version_id = v.registry_version_id
                 WHERE v.registry_version_id = NEW.registry_version_id
                   AND v.generation_id = NEW.generation_id
                   AND a.registry_activation_id = NEW.registry_activation_id
                   AND a.generation_id = NEW.generation_id
                   AND a.registry_revision = NEW.registry_revision
            ) THEN
                RAISE EXCEPTION 'active registry pointer is invalid' USING ERRCODE='23514';
            END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER active_section_registries_validate
        BEFORE INSERT OR UPDATE ON active_section_registries
        FOR EACH ROW EXECUTE FUNCTION dish_validate_active_registry_pointer();
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION dish_validate_task_head_pointer()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM task_content_activations a
                 WHERE a.content_activation_id = NEW.current_content_activation_id
                   AND a.generation_id = NEW.generation_id
                   AND a.task_id = NEW.task_id
                   AND a.task_revision = NEW.task_revision
            ) THEN
                RAISE EXCEPTION 'task content head is invalid' USING ERRCODE='23514';
            END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER task_authority_heads_validate
        BEFORE INSERT OR UPDATE ON task_authority_heads
        FOR EACH ROW EXECUTE FUNCTION dish_validate_task_head_pointer();
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION dish_validate_current_membership()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM task_project_membership_events e
                 WHERE e.membership_event_id = NEW.latest_event_id
                   AND e.generation_id = NEW.generation_id
                   AND e.task_id = NEW.task_id
                   AND e.project_id = NEW.project_id
                   AND e.membership_revision = NEW.membership_revision
                   AND ((e.event_kind = 'joined' AND NEW.is_member)
                     OR (e.event_kind = 'left' AND NOT NEW.is_member))
            ) THEN
                RAISE EXCEPTION 'current project membership pointer is invalid' USING ERRCODE='23514';
            END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER current_task_project_memberships_validate
        BEFORE INSERT OR UPDATE ON current_task_project_memberships
        FOR EACH ROW EXECUTE FUNCTION dish_validate_current_membership();
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION dish_validate_current_placement()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM task_section_placement_events e
                 WHERE e.placement_event_id = NEW.latest_event_id
                   AND e.generation_id = NEW.generation_id
                   AND e.task_id = NEW.task_id
                   AND e.section_id IS NOT DISTINCT FROM NEW.section_id
                   AND e.registry_version_id = NEW.registry_version_id
                   AND e.placement_revision = NEW.placement_revision
            ) THEN
                RAISE EXCEPTION 'current section placement pointer is invalid' USING ERRCODE='23514';
            END IF;
            IF NEW.section_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM section_registry_entries r
                 WHERE r.registry_version_id = NEW.registry_version_id
                   AND r.section_id = NEW.section_id
            ) THEN
                RAISE EXCEPTION 'current placement section is outside registry' USING ERRCODE='23514';
            END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER current_task_section_placements_validate
        BEFORE INSERT OR UPDATE ON current_task_section_placements
        FOR EACH ROW EXECUTE FUNCTION dish_validate_current_placement();
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION dish_validate_current_completion()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM task_completion_events e
                 WHERE e.completion_event_id = NEW.latest_event_id
                   AND e.generation_id = NEW.generation_id
                   AND e.task_id = NEW.task_id
                   AND e.completed = NEW.completed
                   AND e.completion_revision = NEW.completion_revision
            ) THEN
                RAISE EXCEPTION 'current completion pointer is invalid' USING ERRCODE='23514';
            END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER current_task_completion_validate
        BEFORE INSERT OR UPDATE ON current_task_completion
        FOR EACH ROW EXECUTE FUNCTION dish_validate_current_completion();
        """
    )
    for table_name, owner_column in (
        ("project_external_aliases", "project_id"),
        ("section_external_aliases", "section_id"),
        ("task_external_aliases", "task_id"),
    ):
        op.execute(
            f"""
            CREATE OR REPLACE FUNCTION dish_validate_{table_name}_update()
            RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                IF OLD.alias_id <> NEW.alias_id
                   OR OLD.external_system <> NEW.external_system
                   OR OLD.external_id <> NEW.external_id
                   OR OLD.{owner_column} <> NEW.{owner_column}
                   OR OLD.origin <> NEW.origin
                   OR OLD.import_run_id IS DISTINCT FROM NEW.import_run_id
                   OR OLD.projection_event_id IS DISTINCT FROM NEW.projection_event_id
                   OR OLD.created_at <> NEW.created_at THEN
                    RAISE EXCEPTION 'external alias identity is immutable' USING ERRCODE='23514';
                END IF;
                IF OLD.state = 'retired' OR
                   (OLD.state = 'active' AND NEW.state NOT IN ('active','retired')) THEN
                    RAISE EXCEPTION 'illegal external alias transition' USING ERRCODE='23514';
                END IF;
                RETURN NEW;
            END;
            $$;
            CREATE TRIGGER {table_name}_identity_update
            BEFORE UPDATE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION dish_validate_{table_name}_update();
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_task_section_placements')
    op.drop_table('current_task_project_memberships')
    op.drop_table('current_task_completion')
    op.drop_table('task_authority_heads')
    op.drop_table('task_section_placement_events')
    op.drop_table('task_content_activations')
    op.drop_table('section_registry_entries')
    op.drop_table('section_external_aliases')
    op.drop_table('active_section_registries')
    op.drop_table('task_project_membership_events')
    op.drop_table('task_external_aliases')
    op.drop_table('task_content_versions')
    op.drop_table('task_completion_events')
    op.drop_table('section_registry_activations')
    op.drop_table('project_external_aliases')
    op.drop_table('governed_sections')
    op.drop_table('section_registry_versions')
    op.drop_table('governed_projects')
    op.drop_table('generation_bootstrap_authorities')
    op.drop_table('dish_tasks')
    op.drop_table('authority_activations')
    op.drop_table('applied_migration_events')
    op.drop_table('stage_a_import_runs')
    op.drop_table('honest_contract_bindings')
    op.drop_index('uq_authority_generations_one_active', table_name='authority_generations', postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    op.drop_table('authority_generations')
    if op.get_context().dialect.name == "postgresql":
        for function_name in (
            "dish_validate_task_external_aliases_update",
            "dish_validate_section_external_aliases_update",
            "dish_validate_project_external_aliases_update",
            "dish_validate_current_completion",
            "dish_validate_current_placement",
            "dish_validate_current_membership",
            "dish_validate_task_head_pointer",
            "dish_validate_active_registry_pointer",
            "dish_validate_generation_transition",
            "dish_reject_immutable_authority",
        ):
            op.execute(f"DROP FUNCTION IF EXISTS {function_name}()")
    # ### end Alembic commands ###
