"""Immutable DDL snapshot for revision 0007_cutover_evidence_gates."""
from __future__ import annotations

FROZEN_CREATE_SQL_0007 = {
        'postgresql': (
            'CREATE TABLE runtime_release_attestations (\n\tattestation_id UUID NOT NULL, \n\tcandidate_id UUID NOT NULL, \n\tservice_artifact_sha256 VARCHAR(64) NOT NULL, \n\tprojection_worker_artifact_sha256 VARCHAR(64) NOT NULL, \n\troute_probe_sha256 VARCHAR(64) NOT NULL, \n\tpayload JSON NOT NULL, \n\tattestation_sha256 VARCHAR(64) NOT NULL, \n\trecorded_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_runtime_release_attestations PRIMARY KEY (attestation_id), \n\tCONSTRAINT ck_runtime_release_attestations_service_hash_length CHECK (length(service_artifact_sha256) = 64), \n\tCONSTRAINT ck_runtime_release_attestations_worker_hash_length CHECK (length(projection_worker_artifact_sha256) = 64), \n\tCONSTRAINT ck_runtime_release_attestations_route_hash_length CHECK (length(route_probe_sha256) = 64), \n\tCONSTRAINT ck_runtime_release_attestations_attestation_hash_length CHECK (length(attestation_sha256) = 64), \n\tCONSTRAINT uq_runtime_release_attestations_candidate_id UNIQUE (candidate_id), \n\tCONSTRAINT fk_runtime_release_attestations_candidate_id_release_candidates FOREIGN KEY(candidate_id) REFERENCES release_candidates (candidate_id) ON DELETE RESTRICT\n)',
            'CREATE TABLE projection_worker_readiness (\n\treadiness_id UUID NOT NULL, \n\tcandidate_id UUID NOT NULL, \n\tprojection_epoch_id UUID NOT NULL, \n\treconciliation_run_id UUID NOT NULL, \n\tworker_identity VARCHAR(256) NOT NULL, \n\tworker_release VARCHAR(128) NOT NULL, \n\tpayload JSON NOT NULL, \n\treadiness_sha256 VARCHAR(64) NOT NULL, \n\tready_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_projection_worker_readiness PRIMARY KEY (readiness_id), \n\tCONSTRAINT ck_projection_worker_readiness_worker_identity_nonblank CHECK (length(trim(worker_identity)) > 0), \n\tCONSTRAINT ck_projection_worker_readiness_worker_release_nonblank CHECK (length(trim(worker_release)) > 0), \n\tCONSTRAINT ck_projection_worker_readiness_readiness_hash_length CHECK (length(readiness_sha256) = 64), \n\tCONSTRAINT uq_projection_worker_readiness_candidate_id UNIQUE (candidate_id), \n\tCONSTRAINT fk_projection_worker_readiness_candidate_id_release_candidates FOREIGN KEY(candidate_id) REFERENCES release_candidates (candidate_id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_projection_worker_readiness_projection_epoch_id_proj_49b5 FOREIGN KEY(projection_epoch_id) REFERENCES projection_epochs (projection_epoch_id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_projection_worker_readiness_reconciliation_run_id_pr_b5cc FOREIGN KEY(reconciliation_run_id) REFERENCES projection_reconciliation_runs (reconciliation_run_id) ON DELETE RESTRICT\n)',
            'CREATE TABLE first_admission_plans (\n\tplan_id UUID NOT NULL, \n\tcutover_run_id UUID NOT NULL, \n\trequest_id UUID NOT NULL, \n\tcommand_name VARCHAR(64) NOT NULL, \n\ttask_id UUID, \n\texpected_projection_events BIGINT NOT NULL, \n\tpayload JSON NOT NULL, \n\tplan_sha256 VARCHAR(64) NOT NULL, \n\trecorded_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_first_admission_plans PRIMARY KEY (plan_id), \n\tCONSTRAINT ck_first_admission_plans_command_nonblank CHECK (length(trim(command_name)) > 0), \n\tCONSTRAINT ck_first_admission_plans_projection_count_nonnegative CHECK (expected_projection_events >= 0), \n\tCONSTRAINT ck_first_admission_plans_plan_hash_length CHECK (length(plan_sha256) = 64), \n\tCONSTRAINT uq_first_admission_plans_cutover_run_id UNIQUE (cutover_run_id), \n\tCONSTRAINT fk_first_admission_plans_cutover_run_id_cutover_runs FOREIGN KEY(cutover_run_id) REFERENCES cutover_runs (cutover_run_id) ON DELETE RESTRICT, \n\tCONSTRAINT uq_first_admission_plans_request_id UNIQUE (request_id), \n\tCONSTRAINT fk_first_admission_plans_task_id_dish_tasks FOREIGN KEY(task_id) REFERENCES dish_tasks (task_id) ON DELETE RESTRICT\n)',
        ),
        'sqlite': (
            'CREATE TABLE runtime_release_attestations (\n\tattestation_id CHAR(32) NOT NULL, \n\tcandidate_id CHAR(32) NOT NULL, \n\tservice_artifact_sha256 VARCHAR(64) NOT NULL, \n\tprojection_worker_artifact_sha256 VARCHAR(64) NOT NULL, \n\troute_probe_sha256 VARCHAR(64) NOT NULL, \n\tpayload JSON NOT NULL, \n\tattestation_sha256 VARCHAR(64) NOT NULL, \n\trecorded_at DATETIME NOT NULL, \n\tCONSTRAINT pk_runtime_release_attestations PRIMARY KEY (attestation_id), \n\tCONSTRAINT ck_runtime_release_attestations_service_hash_length CHECK (length(service_artifact_sha256) = 64), \n\tCONSTRAINT ck_runtime_release_attestations_worker_hash_length CHECK (length(projection_worker_artifact_sha256) = 64), \n\tCONSTRAINT ck_runtime_release_attestations_route_hash_length CHECK (length(route_probe_sha256) = 64), \n\tCONSTRAINT ck_runtime_release_attestations_attestation_hash_length CHECK (length(attestation_sha256) = 64), \n\tCONSTRAINT uq_runtime_release_attestations_candidate_id UNIQUE (candidate_id), \n\tCONSTRAINT fk_runtime_release_attestations_candidate_id_release_candidates FOREIGN KEY(candidate_id) REFERENCES release_candidates (candidate_id) ON DELETE RESTRICT\n)',
            'CREATE TABLE projection_worker_readiness (\n\treadiness_id CHAR(32) NOT NULL, \n\tcandidate_id CHAR(32) NOT NULL, \n\tprojection_epoch_id CHAR(32) NOT NULL, \n\treconciliation_run_id CHAR(32) NOT NULL, \n\tworker_identity VARCHAR(256) NOT NULL, \n\tworker_release VARCHAR(128) NOT NULL, \n\tpayload JSON NOT NULL, \n\treadiness_sha256 VARCHAR(64) NOT NULL, \n\tready_at DATETIME NOT NULL, \n\tCONSTRAINT pk_projection_worker_readiness PRIMARY KEY (readiness_id), \n\tCONSTRAINT ck_projection_worker_readiness_worker_identity_nonblank CHECK (length(trim(worker_identity)) > 0), \n\tCONSTRAINT ck_projection_worker_readiness_worker_release_nonblank CHECK (length(trim(worker_release)) > 0), \n\tCONSTRAINT ck_projection_worker_readiness_readiness_hash_length CHECK (length(readiness_sha256) = 64), \n\tCONSTRAINT uq_projection_worker_readiness_candidate_id UNIQUE (candidate_id), \n\tCONSTRAINT fk_projection_worker_readiness_candidate_id_release_candidates FOREIGN KEY(candidate_id) REFERENCES release_candidates (candidate_id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_projection_worker_readiness_projection_epoch_id_projection_epochs FOREIGN KEY(projection_epoch_id) REFERENCES projection_epochs (projection_epoch_id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_projection_worker_readiness_reconciliation_run_id_projection_reconciliation_runs FOREIGN KEY(reconciliation_run_id) REFERENCES projection_reconciliation_runs (reconciliation_run_id) ON DELETE RESTRICT\n)',
            'CREATE TABLE first_admission_plans (\n\tplan_id CHAR(32) NOT NULL, \n\tcutover_run_id CHAR(32) NOT NULL, \n\trequest_id CHAR(32) NOT NULL, \n\tcommand_name VARCHAR(64) NOT NULL, \n\ttask_id CHAR(32), \n\texpected_projection_events BIGINT NOT NULL, \n\tpayload JSON NOT NULL, \n\tplan_sha256 VARCHAR(64) NOT NULL, \n\trecorded_at DATETIME NOT NULL, \n\tCONSTRAINT pk_first_admission_plans PRIMARY KEY (plan_id), \n\tCONSTRAINT ck_first_admission_plans_command_nonblank CHECK (length(trim(command_name)) > 0), \n\tCONSTRAINT ck_first_admission_plans_projection_count_nonnegative CHECK (expected_projection_events >= 0), \n\tCONSTRAINT ck_first_admission_plans_plan_hash_length CHECK (length(plan_sha256) = 64), \n\tCONSTRAINT uq_first_admission_plans_cutover_run_id UNIQUE (cutover_run_id), \n\tCONSTRAINT fk_first_admission_plans_cutover_run_id_cutover_runs FOREIGN KEY(cutover_run_id) REFERENCES cutover_runs (cutover_run_id) ON DELETE RESTRICT, \n\tCONSTRAINT uq_first_admission_plans_request_id UNIQUE (request_id), \n\tCONSTRAINT fk_first_admission_plans_task_id_dish_tasks FOREIGN KEY(task_id) REFERENCES dish_tasks (task_id) ON DELETE RESTRICT\n)',
        ),
    }
